name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Compile all C files in src/
        run: |
          mkdir -p bin
          for file in src/*.c; do
            exe="bin/$(basename "${file%.c}")"
            gcc -Wall -Wextra -Werror "$file" -o "$exe"
          done
