name: C/C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make

    - name: Create output directory
      run: mkdir -p build

    - name: Compile C files
      run: |
        echo "Compiling C files..."
        for file in src/*.c; do
          if [ -f "$file" ]; then
            echo "Compiling $file"
            gcc -Wall -Wextra -c "$file" -o "build/$(basename "$file" .c).o" || echo "Failed to compile $file"
          fi
        done

    - name: Compile C++ files
      run: |
        echo "Compiling C++ files..."
        for file in src/*.cpp; do
          if [ -f "$file" ]; then
            echo "Compiling $file"
            g++ -Wall -Wextra -c "$file" -o "build/$(basename "$file" .cpp).o" || echo "Failed to compile $file"
          fi
        done

    - name: List compiled files
      run: |
        echo "Successfully compiled files:"
        ls -la build/