name: Update README

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Update README with program list
      run: |
        echo "# Logic Building Programs" > README.md
        echo "" >> README.md
        echo "This repository contains Java programs for logic building and problem solving." >> README.md
        echo "" >> README.md
        echo "## Program List" >> README.md
        echo "" >> README.md
        
        for file in src/Program*.java; do
          if [ -f "$file" ]; then
            program_name=$(basename "$file" .java)
            echo "- **$program_name**: $(head -n 5 "$file" | grep -o '/\*.*\*/' | sed 's/\/\*//g' | sed 's/\*\///g' | tr -d '\n' || echo 'Java program')" >> README.md
          fi
        done
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "docs: auto-update README with program list"
        git push